### ISSUE TITLE
Great work !!!!

### ISSUE THREAD

**Issue by jeevithakannan2** [ntBre/rwm#19]
Looked at your code, you have done a great job !! I recently jumped from dwm to dwl. I am not planning on returning to X11 because many of the distros have started to remove support for X11 but I would love to try rwl. I am waiting for something like this for wayland, written in pure rust. I am curious to know whether we can add wayland support to rwl ?

**Comment by ntBre** [comment]
Thanks for the kind words! 

I actually took a quick look at the code for [dwl](https://github.com/djpohly/dwl), and, despite sharing many of the function and struct names from dwm, the implementation is basically completely different from dwm and thus rwm, so I don't think rwm would be a useful starting point for a Wayland compositor. I don't use Wayland or have any plans to switch to it, so I don't have any interest in adding Wayland "support" in rwm (such support would require a full rewrite and not really belong under the same project name anyway). 

If the code here is of use to anyone wanting to write such a Wayland compositor, they are welcome to use it under the terms of the MIT license, just like dwm itself.
